- gtfu/src/main/java/gtfu/EmailFailureReporter.java
- gtfu/src/main/java/gtfu/FailureReporter.java
- gtfu/src/main/java/gtfu/GraphicReport.java
- gtfu/src/main/java/gtfu/NullFailureReporter.java
- gtfu/src/main/java/gtfu/RouteCollection.java
- gtfu/src/main/java/gtfu/Util.java
- gtfu/src/main/java/gtfu/tools/SendGrid.java
- gtfu/src/test/java/gtfu/test/LoadAgencyDataTest.java
`LoadAgencyDataTest` pulls a list of agencies from a configurable URL and checks the consistency of their static GTFS data. Failures are recorded and once the test completes, these failures are emailed to recipients listed in the environment variable `GRAAS_REPORT_RECIPIENTS`. 
No slack integration at the moment, since our free plan is constantly out of slack apps, of which we would need one :[
> Test consistency of static GTFS feeds for live agencies

- server/app-engine/util.py
Tested locally with stress-test and confirmed that this method successfully verifies posts (and rejects bad ones)
> remove unnecessary recursion from flask server

- docs/attribution.md
- gtfu/build.gradle
- gtfu/src/main/java/gtfu/ArrivalPrediction.java
- gtfu/src/main/java/gtfu/GraphicReport.java
- gtfu/src/main/java/gtfu/Trip.java
- gtfu/src/main/java/gtfu/TripReportData.java
- gtfu/src/main/java/gtfu/Vehicle.java
- gtfu/src/main/java/gtfu/tools/DayLogSlicer.java
- gtfu/src/main/java/gtfu/tools/TrainingDataUtil.java
- Rename "name" to "headsign" in cases where it actually is the headsign. I have flip-flopped on this in past PRs but believe we're moving towards consistency
- Add RouteCollection is parameter to DayLogSlicer, and have it provide route_name when trip_headsign is null. This required updating TrainingDataUtil.java, something I'm not familiar with and don't know how to test. But ultimately it just replaces a string value with another string value
- Use [ua_parser](https://github.com/ua-parser/uap-java) to parse useragent, os & device from agent field
- Add agent, os, device, uuid & vehicleID to GRaaS report
Potential issues 
- Currently user agent parsing is occurring within TripReportData.java. There is a good argument for creating a file specifically for parsing user agents. That work …
> add new attributes to graphicreport

- gtfu/src/main/java/gtfu/GPSData.java
- gtfu/src/main/java/gtfu/GraphicReport.java
- gtfu/src/main/java/gtfu/tools/DayLogSlicer.java
- gtfu/src/main/java/gtfu/tools/TrainingDataUtil.java
- GPS update dot size increases by 20% of original size for each repeat update sharing same exact latlong. Did this by replacing List<GPSData> with Map<String,GPSData>, which maps each latLong combo with the corresponding GPSData. Increment when already exists.
- Fixes bug where DesertRoadrunner trip names weren't appearing
Potential Issues:
- TrainingDataUtil.java changes remain untested. Will seek guidance on how to test.
> dotsize reflects repeat gps updates

- .github/workflows/pr-test.yaml
- .github/workflows/send-graas-report.yaml
- gtfu/src/main/resources/conf/recipients.json
The current github action <> gcloud auth method is about to be deprecated. The replacement method, storing the service account key json file as a github secret, is supported by google, though it's [not preferred](https://github.com/google-github-actions/auth#setup).
The more robust solution would be setting up a Workload Identify Federation - which would grant a specified level of access to github, and would not be valid except for when github processes are running. I'm open to going with this approach instead - we will need to update some IAM settings in gcloud as a first step.
> Update gcloud auth method

- gtfu/src/main/java/gtfu/GraphicReport.java
The root cause was part of my first change to GRaaS report: creating redundant current-date logic before realizing that current-date was already handled elsewhere. This simplification to the overall code removes the issue.
> Prevent duplicate daily GRaaS reports per agency

- gtfu/src/main/java/gtfu/GPSData.java
- gtfu/src/main/java/gtfu/GraphicReport.java
- gtfu/src/main/java/gtfu/Stats.java
- gtfu/src/main/java/gtfu/TripReportData.java
- gtfu/src/main/java/gtfu/tools/DayLogSlicer.java
- gtfu/src/test/java/gtfu/test/BBSAgentTest.java
This is more cleanup of bugs created early in my GRaaS dev. I had filtered out trips shorter than 15min, but it turns out I had filtered based on schedule rather than GRaaS app sessions. This change removes the faulty logic, and builds new logic to filter out short GRaaS app trips - currently set to a 1min threshold but can be changed easily.
In order to do this, I update the Stats class to accept a list of doubles - and then generate that list before creating each new Stats class instance. This way, it can calculate min and max on two different values within GPSData.
A simpler approach could be to filter out trips with fewer than X location updates (regardless of duration). We could just count the number of items in the map and filter based on that. In my opinion, despite being more …
> Bugfix: filter short trips from GRaaS report

- gtfu/build.gradle
- gtfu/src/main/java/gtfu/GraphicReport.java
- gtfu/src/main/java/gtfu/tools/GCloudBucket.java
- gtfu/src/main/java/gtfu/tools/GCloudStorage.java
- gtfu/src/main/java/gtfu/tools/SendGrid.java
- server/tests/stress-test-config.json
1. Accurate filenames for .png's (ie tcrta-2022-02-09)
2. Save all GRaaS reports to our storage bucket ([archive folder](https://console.cloud.google.com/storage/browser/graas-resources/graas-report-archive?project=lat-long-prototype&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)). Overwrite if it runs multiple times in a day.
3. If there are no reports on a given day, send an email that says "No reports today". (rather than 404 error)
4. Clean up downloadReport/savePath logic, to work as follows: 
- If savePath is given, set downloadReport to true
- If downloadReport is set to true, use a default savePath unless one is also given
- Email sending is no longer tied to download report, so you have option to download report …
> GRaaS report updates in preparation for interactive GRaaS report

- gtfu/src/main/java/gtfu/tools/SendGrid.java
Change broke LoadAgendyData test. Created an [issue](https://github.com/cal-itp/graas/issues/99) for SendGrid unit test.
> resolve changes to sendgrid.java that served only graas report

- gtfu/src/main/java/gtfu/GraphicReport.java
- gtfu/src/main/java/gtfu/tools/GCloudStorage.java
Specifying datatype means you can view images online without downloading. compare the files in [this directory](https://console.cloud.google.com/storage/browser/graas-resources/graas-report-archive/santa-ynez-valley-transit;tab=objects?project=lat-long-prototype&prefix=&forceOnObjectsSortingFiltering=false) with different types to see what I mean.
> specify content type for gcloud upload

- server/app-engine/static/graas.js
PR that was deployed 2 nights ago was not updated with the "agency-params" filename in graas.js. This is not great. Once we removed the filter-params file (around 11AM), requests for the file would fail, and the web app would use default values. Good that we have default values, but it may have created an inconsistent experience for agencies who use different filters.
> correct filter-params to agency-params

- server/app-engine/static/graas.js
- server/app-engine/static/gtfs-rt-util.js
- server/app-engine/templates/index.html
- Check whether agency's agency-config.json contains the optional use-bulk-assignment param (w/ a true value). If so, disable the trip selection dropdown.
- Report the trip-assignment-mode on the in-progress trip data view
- Begin caching vehicle ID, for 4 hours. If a driver stops a trip and starts again, regardless of bulk assignment mode, the vehicle-selection dropdown will auto-populate with the previously-selected value.
- A small amount of general cleanup
> Set up bulk assignment mode (fka "patrol mode")

- server/app-engine/gtfsrt.py
recent changes introduced backfilling of missing trip IDs if possible. The issue is that the code in its current form looks for the name 'trip_id' when the actual name in the update is 'trip-id'.
This leads to all position updates being discarded before adding to DB and server vehicle maps.
As a first step, added tracing output when we discard a position update for missing trip ID.
Then, ran local server confirmed that trace is triggered with updates and current bug. Then, fixed bug and re-ran, confirming that trace is no longer triggered, and furthermore that trip ID backfilling code isn't called.
> fix for 'trip_id' bug

- gtfu/src/main/java/gtfu/tools/UpdateTripNames.java
- server/app-engine/static/graas.js
- server/app-engine/static/gtfs-rt-util.js
- server/app-engine/templates/index.html
- Filter based on logic in GTFS spec
- Filters can be overrided by ignore-start-end-date in agency-params.json
- Test value can be passed in via utm param: testdate
- This PR also removes two unused features: driver-select dropdown and "mode"
For a test agency, I confirmed:
- Filtering will show a trip if the current date is the start date or end date
- Filtering will not show a trip if current date is before start, or after end
- Filtering will show all trips if ignore-start-end-date is set to true (though, cache doesn't refresh immediately)
> Add filtering for calendars.txt start_date and end_date to web app

- gtfu/src/main/java/gtfu/tools/TripListGenerator.java
- server/tests/stress-test-config.json
When a trip has a service_id that is missing from calendar.txt, the most likely reason is that the service_id is instead listed in calendar_dates.txt. This solution simply skips these trips.
This issue caused https://github.com/cal-itp/graas/issues/191
This is a short term patch, and should be addressed long-term via https://github.com/cal-itp/graas/issues/19.
> Update TripListGenerator to omit trips that reference a service_id missing from calendar.txt

- server/app-engine/gtfsrt.py
- server/app-engine/index.yaml
- server/app-engine/static/vehicle-assignments.js
- server/app-engine/util.py
Use a date in the form of yyyy-mm-dd to mark block assignment data validity, instead of unix time stamps. The latter are susceptible to time zone issues, depending on where in the world the client code runs.
I already pushed the index.yaml change, which means the previous dispatch UI won't work until this is merged.
> indicate block assignment data validity using dates, not times

- gtfu/src/main/java/gtfu/Calendar.java
- gtfu/src/main/java/gtfu/CalendarCollection.java
- gtfu/src/main/java/gtfu/Direction.java
- gtfu/src/main/java/gtfu/DirectionCollection.java
- gtfu/src/main/java/gtfu/Route.java
- gtfu/src/main/java/gtfu/RouteCollection.java
- gtfu/src/main/java/gtfu/Time.java
- gtfu/src/main/java/gtfu/Trip.java
- gtfu/src/main/java/gtfu/TripCollection.java
- gtfu/src/main/java/gtfu/Util.java
- gtfu/src/main/java/gtfu/tools/BlockDataGenerator.java
- gtfu/src/main/java/gtfu/tools/TripListGenerator.java
- gtfu/src/test/java/gtfu/test/TestBadStaticGTFS.java
Refactor TLG to use existing functions - and add bits of missing functionality to Util.LoadCollections as needed. Also add Direction and DirectionCollection classes.
I ran UpdateTripNames on all live agencies for a final diff comparison, and the only difference is some rounding on lat and long points. Looks like the result of Float.parseFloat() in StopCollection.java, but I'm inclined to ignore this because: 1) The difference is a matter of feed and 2) It should be now using lat and long values that match the rest of GTFU standard classes. You can see these diffs as they are all sitting in PR drafts.
Separately, I also updated Block Generator to use Util.updateCacheIfNeeded(), as it appears it was using an expired cache. I tested this by re-running the nightly block generation job.
> Refactor TripListGenerator to use Util.LoadCollections

- server/app-engine/main.py
- server/app-engine/static/vehicle-assignments.js
Endpoint for the dispatch edit view remains as `/dispatch-ui`. New read-only access is available through `/show-assignments-only`.
Minimal code changes:
- in javascript initialization routine, check document URL for presence of `show-assignments-only`. If found, hide deploy button and set global read-only flag
- some event handler code is disabled when read-only flag is set
> introduce a read-only view of GTFS block assignments.

- gtfu/src/main/java/gtfu/Time.java
- gtfu/src/main/java/gtfu/Util.java
- gtfu/src/main/java/gtfu/tools/BlockDataGenerator.java
- server/app-engine/static/gtfs-rt-util.js
- server/app-engine/static/vehicle-assignment-index.html
- server/app-engine/static/vehicle-assignment-style.css
- server/app-engine/static/vehicle-assignments.js
- clip labels that are too long and add ellipses, show full label on hover/long press
- show a friendly description for blocks upon click/long press (block ID and then a list of head signs, each with a list of departure times) 
- works for both desktop and mobile
A couple of items that snuck in but aren't actually bulk assignment UI:
- don't choke on missing `directions.txt` in `Util.loadCollections()`
- allow `BlockDataGenerator` to work on agencies not present in agencies.yaml
> bulk assignment UI work

- server/app-engine/static/graas.js
I made these changes as a part of another PR, and thought I'd separate it out for readability. There are no functionality changes here.
- Turned a nested if statement into a standalone "if not this, continue"
- Took out "canvas" and "mode", two unused vars.
- Removed an else clause that handles when trip_names.json has anomalous formatting. This solved for a case that now longer occurs due to automation.
Tested and working fine
> refactoring graas.js

- gtfu/src/main/java/gtfu/tools/GitHubUtil.java
- gtfu/src/main/java/gtfu/tools/UpdateTripNames.java
When small changes to trip-names.json are detected (currently defined by a % difference in byte array length of <5%), automerge the PR rather than waiting for approval.
Also add a flag to UpdateTripNames.json which runs the comparison regardless of whether or not there was a recent update. This is useful for when we update TripListGenerator output and for testing, as it prevents us from having to manually comment out code.
I tested this by editing gtfs files and ensuring that a 5% difference in byte array length correlates to what I intuitively thing that would be (ie just a few lines, depending on length of course).
> Automerge tripname changes

- server/app-engine/static/graas.js
- server/app-engine/static/gtfs-rt-util.js
- server/app-engine/static/index.html
1. When bulk assignment mode is enabled and there is a vehicle ID cached, immediately load the "posting updates" view, with no option to stop trip.
2. When bulk assignment mode is enabled and there is not yet a vehicleID cached, show the vehicle-id dropdown without a "Load trips" button. Once selected and "go" is pressed, load the "posting updates" view, with no option to stop trip.
3. Normal behavior when bulk assignment mode is not enabled. Auto populate vehicleID dropdown (it can be manually changed though)
> Reduce friction for bulk assignment mode

- gtfu/src/test/java/gtfu/test/LoadAgencyDataTest.java
[This issue](https://github.com/cal-itp/graas/issues/292) occurred last night, when connection to CAE gtfs url timed out. The initial issue, at least, is that our LoadAgencyData test email showed up clean for CAE, when it should have showed an error message. This update includes errors loading their into the email.
It doesn't address the root cause of the connection timing out, but I'm not yet convinced that we have control over that issue.
> include more failures to LoadAgencyDataTest email

- server/app-engine/requirements.txt
Huffing along on the deprecation treadmill: as of today, server deploys would fail catastrophically with the server dying on startup, and clients getting `HTTP ERROR 502 Bad Gateway`.
python package and server sub-dependency `protobuf` had a release last Friday, which seems to cause serious issues. Explicitly pinning version for `protobuf` to 3.20.1.
Tested by deploying to staging, then 1) curling the target URL and 2) running a node test to push a position update. Both tests will fail if deploy is unsuccessful.
> fix server deployment

- gtfu/src/main/java/gtfu/CalendarCollection.java
When we create the validity period for a calendar, make it so that it spans until the end of the last day, not just the beginning of the last day.
This caused problems for the block data generator for sure, but probably also led to other failures
> bugfix for block data generator

- docs/CONTRIBUTING.md
Checked out a few different open source projects and some of them call out the code of conduct int he contribution guidelines and readme.
> Added reference for Code of Conduct

- server/app-engine/static/vehicle-assignments.js
Previously, blocks and vehicles were sometimes drawn off-screen.
Tested layout with various screen sizes and confirmed that all elements are visible.
> fix element layout in dispatch UI

- .gitignore
- tools/smoke-test.sh
Being able to only debug test failures through git push is very cumbersome. An added wrinkle here is that it appears as if github always runs the main branch version of pr-test.yaml, which in a way is of course what you want, but also makes debugging test issues in a branch that much hairier.
Run local smoke test with tools/smoketest.sh.
Test will bail if the following env vars aren't set:
PR_TEST_URL: server URL
PR_TEST_ID_ECDSA: private key for pr-test agency
PR_TEST_GRAAS_VENV: path to python virtual env created from server/app-engine/requirements.txt
> Add local version of .github/workflows/pr-test.yaml.

- .github/workflows/pr-test.yaml
Our pr-test github action started failing because it runs on `ubuntu-latest`, which is a moving target. It was [upgraded from 20.04 to 22.04](https://github.com/actions/runner-images/issues/6399) last month, which no longer carried our required version of python. This change pins ubuntu to the previous version, so everything works...for now.
> resolve versioning issues to get pr-test working

- gtfu/src/main/java/gtfu/tools/StaticGTFSToBucket.java
I updated the existing gtfs archive process to save a copy of the raw zip file to 
[graas-resources/gtfs-mirror](https://console.cloud.google.com/storage/browser/graas-resources/gtfs-mirror;tab=objects?project=lat-long-prototype&prefix=&forceOnObjectsSortingFiltering=false). Please look at the directory and let me know if this matches the need!
> save raw zip file to grass-resources/gtfs-mirror/agency-name.zip

- server/app-engine/static/graas.js
We previously removed for any number of reasons, including no network connectivity. Adapted to only remove upon failure to load key from token, which is a good indicator that token is corrupt.
Tested by temporarily changing the `/hello` URL to something bogus  and back repeatedly, and observing resulting behavior.
> Be more thoughtful about removing agency token. 

- .github/workflows/graas-bot.yaml
- server/app-engine/ecdsa-test.py
- server/app-engine/graas_bot.py
- server/app-engine/main.py
- server/app-engine/requirements.txt
- server/app-engine/static/graas.js
- create grass bot that collects usage stats and posts to slack channel at 11 pm PT every day
- make all server endpoints follow the designated signature verification approach, instead of fragmented local variations
- fix issues around initial token verification 
- allow python code to produce grass-compatible ECDSA keys with a couple of lines of code, instead of tedious command line sequences or brittle system calls from within python (see ecdsa-test.py for an example on how to generate)
- tested token verification, position updates and alert updates
> automation groundwork
