cal-itp/graas

gtfu/src/main/java/gtfu/ArrivalPrediction.java, gtfu/src/main/java/gtfu/GraphicReport.java, gtfu/src/main/java/gtfu/Trip.java, gtfu/src/main/java/gtfu/TripReportData.java, gtfu/src/main/java/gtfu/Vehicle.java, gtfu/src/main/java/gtfu/tools/DayLogSlicer.java, gtfu/src/main/java/gtfu/tools/GPSLogSlicer.java
Updated some nomenclature, moved functions around between classes, added comments. Poorly named branch.
Some nomenclature standards I am trying to use:
**route**: the name of a transit route, not tied to a specific time
**trip**: an instance of a route occurring at a specific time
**name**: other, often somewhere in the middle
=> graphic report refactor

server/app-engine/log-filter.py
- flush stdout (piping tool output to other command won't work otherwise)
- formatting change
- handle ctrl-c more gracefully
=> for log filter:

gtfu/src/main/java/gtfu/TripReportData.java, gtfu/src/test/java/gtfu/test/BBSAgentTest.java
=> - custom logic for BBS user agents

gtfu/src/main/java/gtfu/tools/GTFSValidator.java
grabbed the latest version of the validator
=> update to current gtfs-validator

docs/attribution.md
add attribution for html-qrcode
=> add missing attribution

gtfu/src/main/resources/conf/recipients.json
Reverts cal-itp/graas#80
Created https://github.com/cal-itp/graas/issues/82 for better solution
=> Revert "add slack email to GRaaS report recipients"

server/app-engine/static/graas.js
- Added DOW as a UTM parameter
- Replaced naked strings that appear more than once with symbolic constants.
- There are one or two dozen more one-off strings that could be replaced as well
=> add DOW as utm param, replace naked strings

server/app-engine/static/graas.js, server/app-engine/static/gtfs-rt-util.js, server/app-engine/templates/index.html
Prior to deploying last night I noticed a bug - the "Loading GRaaS" appears below the "Load trips" button for a split second after scanning QR code. This PR resolves that issue, and also does another pass at limiting logging
=> fix bug, remove logging

server/app-engine/static/gtfs-rt-util.js, server/app-engine/static/nosleep.js, server/app-engine/templates/index.html
- fix nosleep.js breakage for safari on some iOS 15.x devices
- fix broken app-internal, togglable, on-screen console
- fix broken touch screen events
- reroute mouse events to touch screen handler code to enable easier desktop debugging
=> fix for: nosleep.js broken for some iOS 15.x devices

gtfu/src/main/java/gtfu/RealtimeVisualization.java, gtfu/src/main/java/gtfu/Trip.java, gtfu/src/main/java/gtfu/TripScheduleCollection.java, gtfu/src/main/java/gtfu/Util.java, gtfu/src/main/java/gtfu/tools/AgencyYML.java, gtfu/src/main/java/gtfu/tools/ShapeBrowser.java, gtfu/src/test/java/gtfu/test/TestBadStaticGTFS.java
Use like so: java -cp build/libs/gtfu.jar gtfu.tools.ShapeBrowser -a tcrta -c ~/tmp/tuff D1 D2 D3 D4
Any unnamed args are assumed to be shape IDs. In the browser, use 'n' and 'p' to navigate between shapes.
=> a simple graphical GTFS shape browser

gtfu/src/main/java/gtfu/Block.java, gtfu/src/main/java/gtfu/BlockCollection.java, gtfu/src/main/java/gtfu/ShapeCollection.java, gtfu/src/main/java/gtfu/Trip.java, gtfu/src/main/java/gtfu/TripCollection.java, gtfu/src/main/java/gtfu/Util.java, gtfu/src/main/java/gtfu/tools/ShapeBrowser.java
- add GTFS blocks to gtfu
- if no shape IDs are given as ShapeBrowser args, load and show all shapes for agency
=> GTFS blocks and shape browser upgrade

gtfu/src/main/java/gtfu/BlockCollection.java, gtfu/src/main/java/gtfu/tools/BlockDataGenerator.java
Use like so: `java -cp build/lib/gtfu.jar gtfu.tools.BlockDataGenerator -c <cache-folder> -a <agency-id>`
=> tool to generate mappings from block IDs to trip IDs

server/app-engine/log-filter.py
=> don't let log filter choke on json parsing issues

docs/server/README.md, server/app-engine/requirements.txt
Also update a bit of documentation
I will deploy this tonight to staging and perform a lot of testing prior to routing traffic
=> Upgrade flask to (hopefully) enable deploy

gtfu/src/main/resources/conf/recipients.json
=> Update recipients.json to include Ali in tech reports

server/app-engine/static/vehicle-assignment-style.css, server/app-engine/static/vehicle-assignments.js
- fix a couple of "dirty" state bugs
- rounded corners and box shadow for toast and modals
=> bug fix and minor UI cleanup

gtfu/src/main/java/gtfu/tools/BlockDataGenerator.java, server/app-engine/.gcloudignore, server/app-engine/gtfsrt.py, server/app-engine/requirements.txt, server/app-engine/static/graas.js, server/app-engine/static/vehicle-assignments.js, server/app-engine/templates/index.html, server/app-engine/templates/vehicle-assignment-index.html, server/app-engine/util.py
- fix crash bug in BlockDataGenerator for absolute dates
- make server dates timezone aware
- fix timezone bug
- fix erratic zoom behavior by disabling pinch-to-zoom
=> bulk assignment bug fixes

server/app-engine/app.yaml
see https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml#updated_health_checks
=> add liveness and readiness health checks

docs/python-docs.md, mkdocs.yml, server/app-engine/gtfsrt.py, server/app-engine/main.py, server/app-engine/util.py
Requires the following pip installs:
- mkdocstrings
- mkdocs
- mkdocs-material
I haven't added these to requirements.txt, as otherwise they would be installed in app-engine for deploys. Open to ideas on how to better handle these doc dependencies.
=> Create python docstrings for server code, integrate into mkdocs

server/app-engine/static/graas.js, server/app-engine/static/gtfs-rt-util.js, server/app-engine/static/vehicle-assignments.js, server/tests/README.md
- fix long press race condition in dispatch UI, as reported by @owades
- export util time constants
- fix internal call of getTimeFromString()
tested grass client and dispatch UI on mobile
=> fix some JS issues, including stuck dispatch UI on mobile

.github/workflows/pr-test.yaml, server/app-engine/static/graas.js, server/app-engine/static/gtfs-rt-util.js, server/app-engine/static/vehicle-assignments.js, server/tools/eslint/config.js, server/tools/eslint/lint-files.sh
- Update eslint to not fail for currently common issues, and to run as a part of PR test. 
- Make updates mainly to graas.js, gtfs-rt-util.js and vehicle-assignments.js, in order to pass the no-redeclare test. One of the bigger changes here is introducing let instead of var
- Note that I haven't yet figured out how to have eslint catch the duplicate variable issue that was resolved in #241 - still working at it.
I would appreciate a detailed look at the vehicle-assignments.js changes, as this is not code I'm completely familiar with.
=> setup eslint and perform initial set of fixes

docs/server/README.md, server/app-engine/gtfsrt.py, server/app-engine/main.py
Fixed work both in staging server and local.
=> Fix bug in pb tests

gtfu/src/main/java/gtfu/GraphicReport.java, gtfu/src/main/java/gtfu/Point.java, gtfu/src/main/java/gtfu/tools/AgencyListGenerator.java, gtfu/src/main/java/gtfu/tools/BlockDataGenerator.java, gtfu/src/main/java/gtfu/tools/GCloudStorage.java, gtfu/src/web/graas-report-web.js, gtfu/src/web/index.html, gtfu/src/web/style.css
Add two new features:
- Animate a trip upon click
- Zoom to a trip upon shift+click
Some general refactoring of GraphicReport as well, and retrofitting it to produce images both with and without vehicle positions.
Preview the dashboard [here](https://storage.googleapis.com/graas-resources/web/test/index.html)
One bug I just identified is that the instructions popup only appears when scrolled all the way to the top. Will work on it.
=> Add animation & zoom to GRaaS Report Dashboard

gtfu/src/main/java/gtfu/GraphicReport.java, gtfu/src/web/graas-report-web.js
trip_id and vehicle_id are appearing as undefined:
=> Fix null value in graas report dashboard metadata

server/app-engine/gtfsrt.py, server/app-engine/util.py
more testing uncovered a few more issues:
- update block_collection['last-refresh'] after checking liveness
- proper number padding for util.get_yyyymmdd()
- reduce tracing verbosity some
=> more trip updates clean-up

server/app-engine/gtfsrt.py, server/tests/README.md, server/tests/post-vehicle-positions.js
- ensure source fields for entity selectors don't just exist, but are of type string
- fix some diagnostic output for post-vehicle-positions.js
- fix typo in server/tests/README.md
=> DB batch write addendum

gtfu/src/main/java/gtfu/RouteCollection.java, gtfu/src/main/java/gtfu/Util.java
- for missing route colors, we are already handling the case where the column exists but a row value is missing. We now also handle the case where the column is missing
- handle missing calendar.txt file gracefully
=> robustness fixes

.gitignore, docs/new-instance-setup.md, server/app-engine/db-test.py, server/app-engine/db.py, server/app-engine/gtfsrt.py, server/app-engine/requirements-cloudless.txt, server/app-engine/requirements.txt, server/app-engine/util.py
Let users curious about GRaaS run a server locally without the need for a google cloud account or project.
Steps:
- create a venv using `server/app-engine/requirements-cloudless.txt`
- activate venv
- run `python main.py -c <path-to-cert.pem> -k <path-to-key.pem>` # pem files constitute self-signed https cert
I ran the following tests for local cloudless server, local server and staging server:
- create and deploy bulk assignment
- run web app in bulk assignment mode and observer backfiling of trip IDs from assignment
- post-vehicle-positions
- post-service-alerts
- post-stop-time-entities
=> cloud-free setup for eval purposes

.gitignore, server/tests/README.md, server/tests/tee-test.js, server/tests/tee.js
- poc implementation of tee for node
- tee test
- see README for usage
=> minimal tee for node

server/tests/tee-test.js, server/tests/tee.js
- capture console.log() traces
- don't reassign stdout
- less code
=> tee improvements

server/app-engine/static/graas.js
add trip filter override for the web app in the form of url arg `usefilters=<true|false>`. If set to `false` then no trip filtering occurs. Defaults to `true`.
Tested locally with `plumas-transit-systems` as agency running web app in desktop browser against local server instance. Results: trip list empty (as expected) when arg not given, and trip list populated when arg given. Confirmed that position updates are accepted by server in latter case.
=> trip filter override for the web app

server/qr-gen/src/main/java/qrgen/Main.java
This is one step toward a more robus…t user/troubleshooting experience.
=> embed creation date on QR codes

server/app-engine/main.py, server/app-engine/static/graas.js
Tested with both valid and invalid keys to confirm correct behavior.
=> Verify that agency token contains a key recognized by backend before persisting to local storage

server/app-engine/keygen.py, server/app-engine/main.py, server/app-engine/util.py
- replace brittle system calls to external crypto tools with native python code
- check if agency ID already exists before generating keys
- scaffolding for web-admin routes in server with draft flow outlines
=> first steps for web admin automation

gtfu/src/main/java/gtfu/MonitorPositionUpdates.java
reminder: use `./scripts/monitor-position-updates.sh` to run MonitorPositionUpdates tool, `-url <url>` to set feed URL and `-api-key <api-key>` to set API key.
Tested with NYC MTA.
=> add support for realtime feeds that require an API key for access
